### ISSUE TITLE
Error:No OpKernel was registered to support Op 'CudnnRNNParamsSize'

### ISSUE THREAD

**Issue by kingjg** [HKUST-KnowComp/R-Net#17]
Hi,
I ran the python3 ./config.py --mode train as the readme suggests, and then the error in the title occurred. I really don't know what went wrong, please help me!!!
the error information is posted as follows:
```bash
/usr/lib/python3.4/importlib/_bootstrap.py:321: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  return f(*args, **kwds)
Building model...
2018-01-29 16:26:08.747856: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1293, in _run_fn
    self._extend_graph()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1354, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNNParamsSize' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: match/CudnnRNNParamsSize_1 = CudnnRNNParamsSize[S=DT_INT32, T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", rnn_mode="gru", seed=87654321, seed2=0](match/CudnnRNNParamsSize_1/num_layers, match/CudnnRNNParamsSize_1/num_units, match/CudnnRNNParamsSize_1/input_size)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "config.py", line 127, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "config.py", line 108, in main
    train(config)
  File "/home/yx/ssd/R-Net-master/main.py", line 46, in train
    sess.run(tf.global_variables_initializer())
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNNParamsSize' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: match/CudnnRNNParamsSize_1 = CudnnRNNParamsSize[S=DT_INT32, T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", rnn_mode="gru", seed=87654321, seed2=0](match/CudnnRNNParamsSize_1/num_layers, match/CudnnRNNParamsSize_1/num_units, match/CudnnRNNParamsSize_1/input_size)]]

Caused by op 'match/CudnnRNNParamsSize_1', defined at:
  File "config.py", line 127, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "config.py", line 108, in main
    train(config)
  File "/home/yx/ssd/R-Net-master/main.py", line 35, in train
    model = Model(config, iterator, word_mat, char_mat)
  File "/home/yx/ssd/R-Net-master/model.py", line 43, in __init__
    self.ready()
  File "/home/yx/ssd/R-Net-master/model.py", line 107, in ready
    ).as_list()[-1], keep_prob=config.keep_prob, is_train=self.is_train)
  File "/home/yx/ssd/R-Net-master/func.py", line 24, in __init__
    [gru_bw.params_size()], -0.1, 0.1), validate_shape=False)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 1305, in params_size
    direction=self._direction)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 1208, in cudnn_rnn_opaque_params_size
    name=name)[0]
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/cudnn_rnn/ops/gen_cudnn_rnn_ops.py", line 439, in cudnn_rnn_params_size
    seed=seed, seed2=seed2, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'CudnnRNNParamsSize' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: match/CudnnRNNParamsSize_1 = CudnnRNNParamsSize[S=DT_INT32, T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", rnn_mode="gru", seed=87654321, seed2=0](match/CudnnRNNParamsSize_1/num_layers, match/CudnnRNNParamsSize_1/num_units, match/CudnnRNNParamsSize_1/input_size)]]

```

**Comment by wzhouad** [comment]
Seems that you don't have GPU or the GPU is not correctly configured. Set use_cudnn to False in config.py to run with CPU.

**Comment by kingjg** [comment]
Thanks, it really works! By the way, could you tell me how long it takes for you to train the model? it seems to take really long time to train the model without cudnn.

**Comment by wzhouad** [comment]
It depends on the device. It takes two days to train the model on TITAN X without cudnn.

**Comment by kingjg** [comment]
OK,thanks!
