### ISSUE TITLE
bucket range type error

### ISSUE THREAD

**Issue by mickyyu96** [HKUST-KnowComp/R-Net#28]
Hello, i got some issue.
When i run 'python config.py --mode prepro' or other mode i got the error below.
How to solve this ?

`Traceback (most recent call last):
  File "/home/m13514063/anaconda3/envs/micky/lib/python3.5/site-packages/absl/flags/_flag.py", line 166, in _parse
    return self.parser.parse(argument)
  File "/home/m13514063/anaconda3/envs/micky/lib/python3.5/site-packages/absl/flags/_argument_parser.py", line 152, in parse
    val = self.convert(argument)
  File "/home/m13514063/anaconda3/envs/micky/lib/python3.5/site-packages/absl/flags/_argument_parser.py", line 268, in convert
    type(argument)))
TypeError: Expect argument to be a string or int, found <class 'list'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "config.py", line 80, in <module>
    flags.DEFINE_integer("bucket_range", [40, 401, 40], "the range of bucket")
  File "/home/m13514063/anaconda3/envs/micky/lib/python3.5/site-packages/tensorflow/python/platform/flags.py", line 58, in wrapper
    return original_function(*args, **kwargs)
  File "/home/m13514063/anaconda3/envs/micky/lib/python3.5/site-packages/absl/flags/_defines.py", line 315, in DEFINE_integer
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/home/m13514063/anaconda3/envs/micky/lib/python3.5/site-packages/absl/flags/_defines.py", line 81, in DEFINE
    DEFINE_flag(_flag.Flag(parser, serializer, name, default, help, **args),
  File "/home/m13514063/anaconda3/envs/micky/lib/python3.5/site-packages/absl/flags/_flag.py", line 107, in __init__
    self._set_default(default)
  File "/home/m13514063/anaconda3/envs/micky/lib/python3.5/site-packages/absl/flags/_flag.py", line 196, in _set_default
    self.default = self._parse(value)
  File "/home/m13514063/anaconda3/envs/micky/lib/python3.5/site-packages/absl/flags/_flag.py", line 169, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --bucket_range=[40, 401, 40]: Expect argument to be a string or int, found <class 'list'>`

**Comment by mickyyu96** [comment]
i solve it with changing DEFINE_integer to DEFINE_list.

**Comment by utkarshpandey12** [comment]
I am facing same issue how do you fix these errors
