### ISSUE TITLE
Using fasttext pre-trained embedding

### ISSUE THREAD

**Issue by NewEnglandML** [HKUST-KnowComp/R-Net#44]
Hi, If the boolean flags for fasttext changed to True, the pre processing does not work properly. The modification for config.py is more that changing the size of embedding or not?

**Comment by wzhouad** [comment]
The error may be caused by missing dataset. Uncomment the corresponding line in download.sh to download it.

**Comment by NewEnglandML** [comment]
I have uncommented that line, when running config.py --mode prepro, during the creating the word embedding the error appears:

Traceback (most recent call last):
  File "config.py", line 134, in <module>
    tf.app.run()
  File "/home/farshid/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "config.py", line 119, in main
    prepro(config)
  File "/home/farshid/Desktop/tensorflow/New_RNET/R-Net-0.1 (copy)/prepro.py", line 223, in prepro
    size=config.glove_word_size, vec_size=config.glove_dim, token2idx_dict=word2idx_dict)
  File "/home/farshid/Desktop/tensorflow/New_RNET/R-Net-0.1 (copy)/prepro.py", line 116, in get_embedding
    for token, idx in token2idx_dict.items()}
  File "/home/farshid/Desktop/tensorflow/New_RNET/R-Net-0.1 (copy)/prepro.py", line 116, in <dictcomp>
    for token, idx in token2idx_dict.items()}
KeyError: "n't"
