### ISSUE TITLE
Error when context is too short

### ISSUE THREAD

**Issue by ericchansen** [HKUST-KnowComp/R-Net#52]
### What is the best way to deal with short contexts?

I believe this implementation fails when the context is less than 15 tokens due to `outer = tf.matrix_band_part(outer, 0, 15)`, which is located at https://github.com/HKUST-KnowComp/R-Net/blob/master/inference.py#L111.

#### Code Snippet

```
    with tf.variable_scope("predict"):
            outer = tf.matmul(tf.expand_dims(tf.nn.softmax(logits1), axis=2),
                              tf.expand_dims(tf.nn.softmax(logits2), axis=1))
            outer = tf.matrix_band_part(outer, 0, 15)
            self.yp1 = tf.argmax(tf.reduce_max(outer, axis=2), axis=1)
            self.yp2 = tf.argmax(tf.reduce_max(outer, axis=1), axis=1)
```

#### Example

For example, consider 2 contexts.

`The N64 was released in Japan on June 23, 1996.`
`The N64, Nintendo's third game console, was released in Japan on June 23, 1996.`

`When was the N64 released?` works for the 2nd context, but the 1st context throws an error.

#### Modified `__main__` From `inference.py`

```
if __name__ == "__main__":
    infer = Inference()
    context = \
        "The N64 was released in Japan on June 23, 1996."
    ques1 = "When was the N64 released?"
    ans1 = infer.response(context, ques1)
    print("Answer 1: {}".format(ans1))
```

#### Error Message

```
/home/eric/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From /home/eric/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Traceback (most recent call last):
  File "/home/eric/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call    return fn(*args)
  File "/home/eric/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/eric/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/home/eric/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: num_upper must be negative or less or equal to number of columns (12) got: 15
         [[Node: predict/MatrixBandPart = MatrixBandPart[T=DT_FLOAT, Tindex=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](predict/MatMul, predict/MatrixBandPart/num_lower, predict/MatrixBandPart/num_upper)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 231, in <module>
    ans1 = infer.response(context, ques1)
  File "inference.py", line 140, in response
    model.c: context_idxs, model.q: ques_idxs, model.ch: context_char_idxs, model.qh: ques_char_idxs})
  File "/home/eric/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/eric/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/eric/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/home/eric/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: num_upper must be negative or less or equal to number of columns (12) got: 15
         [[Node: predict/MatrixBandPart = MatrixBandPart[T=DT_FLOAT, Tindex=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](predict/MatMul, predict/MatrixBandPart/num_lower, predict/MatrixBandPart/num_upper)]]

Caused by op 'predict/MatrixBandPart', defined at:
  File "inference.py", line 194, in <module>
    infer = Inference()
  File "inference.py", line 127, in __init__
    self.model = InfModel(self.word_mat, self.char_mat)
  File "inference.py", line 55, in __init__
    self.ready()
  File "inference.py", line 111, in ready
    outer = tf.matrix_band_part(outer, 0, 15)
  File "/home/eric/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3464, in matrix_band_part
    num_upper=num_upper, name=name)
  File "/home/eric/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/eric/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op    op_def=op_def)
  File "/home/eric/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): num_upper must be negative or less or equal to number of columns (12) got: 15
         [[Node: predict/MatrixBandPart = MatrixBandPart[T=DT_FLOAT, Tindex=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](predict/MatMul, predict/MatrixBandPart/num_lower, predict/MatrixBandPart/num_upper)]]
```

**Comment by ericchansen** [comment]
Can anyone explain the impact of simply changing `outer = tf.matrix_band_part(outer, 0, 15)` to something like `outer = tf.matrix_band_part(outer, 0, 8)`?

**Comment by maciejbiesek** [comment]
It may causes drop in performance (eg. during evaluation on SQuAD), because it means that answer is gonna be maximum of length 15 tokens, so of course the given passage has to have at least 15 tokens.
